version: '3'

services:
  apache:
    image: httpd:2.4
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/httpd/logs/access_log:/usr/local/apache2/logs/access_log
      - ./docker/httpd/logs/error_log:/usr/local/apache2/logs/error_log
    depends_on:
      - php

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./htdocs:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - apache

  php:
    image: php:7.2-fpm
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./tmp:/tmp
